name: build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Check ollama
        run: ollama -v

      - name: Delete existing key
        run: |

      - name: Generate key for ollama
        run: |
          rm /usr/share/ollama/.ollama/id_ed25519
          rm /usr/share/ollama/.ollama/id_ed25519.pub
          echo "${{ secrets.ID_ED25519 }}" > /usr/share/ollama/.ollama/id_ed25519
          echo "${{ secrets.ID_ED25519_PUB }}" > /usr/share/ollama/.ollama/id_ed25519.pub
          chmod 600 /usr/share/ollama/.ollama/id_ed25519
          chmod 600 /usr/share/ollama/.ollama/id_ed25519.pub
          ls -al /usr/share/ollama/.ollama/id_ed25519

      - name: Download base model
        run: curl -L -O https://huggingface.co/heegyu/EEVE-Korean-Instruct-10.8B-v1.0-GGUF/resolve/main/ggml-model-Q5_K_M.gguf?download=true

      - name: Check files
        run: ls -al

      - name: Create Model
        run: ollama create lancard/korean-yanolja-eeve -f Modelfile

      - name: Push Model
        run: ollama push lancard/korean-yanolja-eeve
